import type { CauseAnalysis } from "./causeai-api";

export function generatePostmortemContent(analysis: CauseAnalysis) {
  const now = new Date().toLocaleString();
  const cascade = analysis.cascadeChain.join(" -> ");
  const services = analysis.affectedServices
    .map((service) => `- **${service.name || "unknown"}** - ${service.status || "unknown"}${service.role ? ` (${service.role})` : ""}`)
    .join("\n");
  const timeline = analysis.timeline
    .map((item) => `- \`${item.time || "--:--:--"}\` ${item.event || item.description || ""}${item.service ? ` [${item.service}]` : ""}`)
    .join("\n");
  const alternatives = analysis.alternatives
    .map((alt) => `- ${alt.cause || "Unknown"} (${alt.confidence ?? 0}% confidence)`)
    .join("\n");

  return `# Incident Postmortem
*Generated: ${now}*

## Severity
**${analysis.severity}** - Confidence: ${analysis.confidenceScore}%

## Root Cause
${analysis.rootCause}

**Primary service:** ${analysis.rootCauseService}

## Business Impact
${analysis.businessImpact || "Not assessed"}

## Affected Services
${services || "None identified"}

## Failure Cascade
${cascade || "N/A"}

## Timeline
${timeline || "No timeline available"}

## Immediate Remediation
${analysis.immediateFix || "See engineering team"}

## Long-Term Prevention
${analysis.permanentFix || "See engineering team"}

## Alternatives Considered
${alternatives || "None"}

---
*Generated by CauseAI*`;
}

